theme: jekyll-theme-cayman
title: Interpreting Video Features of Deep Net Classifiers
description: Supplementary material displaying further qualitative results for the paper Interpreting video features: A comparison of 3D Convolutional networks and Convolutional LSTM networks 
